Duty.yaml
Subscription.yaml
common.yaml
paths/subscriptions.yaml

Lite mera förfinade events att abonnera på

Subscription

---

ChildCareSchedule.yaml
misc.txt
openapi.yaml
paths/attendanceEvents.yaml
paths/calendarEvents.yaml
paths/childcareSchedule.yaml

Added an endpoint for ChildCareSchedule 
Fixed some typos

Endpoint for ChildCareSchedule

---

LeaveOfAbsence.yaml
common.yaml
openapi.yaml
paths/leaveofabsences.yaml
todo.txt

Create a new LeaveOfAbsence

---

Activity.yaml
LeaveOfAbsence.yaml
openapi.yaml
paths/activities.yaml
paths/duties.yaml
paths/grades.yaml
paths/leaveofabsences.yaml
paths/organisations.yaml
todo.txt

fixed non valid openapi

---

StudyPlan.yaml
openapi.yaml
paths/studyPlans.yaml

StudyPlan paths

---

Activity.yaml

TK-450-AG10 version2 rev18: 5.5.17: Activity:
Giltiga kombinationer av Aktiviteter:
—	Ämne – Lärare
—	Kurs – Lärare
—	Ämne – Grupp
—	Kurs – Grupp
—	Grupp – Lärare
—	Ämne – Elev
—	Kurs – Elev
—	Elev – Lärare

Activity.yaml: Replaced required groups to owner

---

Grade.yaml
LeaveOfAbsence.yaml
StudentGroup.yaml
Syllabus.yaml

Fixed syntax errors

---

Person.yaml

Updated person, added/changed relational properties:
- repsonsibleRelations
- relations
- association
Added address type:  Särskildpostadres 
Added new properties in the addresses:
- countyCode
- municipalityCode
- realEstateDesignation

Updated person

---

paths/aggregatedAttendances.yaml
paths/persons.yaml
paths/placements.yaml
paths/programmes.yaml
paths/resources.yaml
paths/rooms.yaml
todo.txt

En del är otydligt, bör vi ha Desc explicit eller inte ?
fixade en dålig path i aggregatedAttendances.yaml

Från min lista

---

Duty.yaml
StudentGroup.yaml
common.yaml
paths/duties.yaml

I have noted that we said that we should have an expand on duty to assignmentRoles,
since no-one seems to have made on this is my suggestion

Missed an expand on Duty

---

Duty.yaml
StudentGroup.yaml
Subscription.yaml
common.yaml
paths/duties.yaml
paths/subscriptions.yaml

Some minor changes to subscriptions.
Snake_case to camelCase on props.
A triggeredAt on the callback.
A active status  on the get of subscription.
Based on the duty expand ci.

Subscriptions 

---

common.yaml
openapi.yaml
paths/absences.yaml
paths/activities.yaml
paths/attendances.yaml
paths/duties.yaml
paths/grades.yaml
paths/organisations.yaml
paths/persons.yaml
paths/placements.yaml
paths/programmes.yaml
paths/resources.yaml
paths/rooms.yaml
paths/schoolUnitOfferings.yaml
paths/schoolUnits.yaml
paths/studentGroups.yaml
paths/syllabuses.yaml

Ändrat alla POST /X/filter till /X/lookup
La till en common ref för enkel Id Lookup
Ändrade person, placement och attendance till att ta en varianter av id (som att de föll bort från GET)

Use lookup instead of filter on POST

---

common.yaml
funderingar.txt
paths/absences.yaml
paths/activities.yaml
paths/aggregatedAttendances.yaml
paths/attendances.yaml
paths/calendarEvents.yaml
paths/childCareAttendanceEvents.yaml
paths/childcareSchedule.yaml
paths/duties.yaml
paths/grades.yaml
paths/organisations.yaml
paths/persons.yaml
paths/placements.yaml
paths/programmes.yaml
paths/resources.yaml
paths/rooms.yaml
paths/schoolUnitOfferings.yaml
paths/schoolUnits.yaml
paths/searchParameters.yaml
paths/studentGroups.yaml
paths/studyPlans.yaml
paths/syllabuses.yaml

All object references containing displayName that it should only be resolved when the param expandReferenceNames is set to true.

Made displayName controllable by the expandReferenceNames param

---

SchoolUnitOffering.yaml
paths/schoolUnitOfferings.yaml

Uppdaterade SchoolUnitOffering så att dem stämmer med wordfilen.

School unit offering alignment

---

Enrolment.yaml
Programme.yaml
SchoolUnitOffering.yaml
openapi.yaml
paths/deletedEntities.yaml
paths/programmes.yaml
paths/schoolUnitOfferings.yaml
paths/studyPlans.yaml
paths/syllabuses.yaml

Updated datastructure for progrmmes, it's now recursive.
Fixed a minor issue with deletedEntires.
Added a pointer to programmes from enrolements.

Updated enrolement / programme

---

SchoolUnitOffering.yaml
openapi.yaml
paths/schoolUnitOfferings.yaml

Kunde inte få det att bygga men detta kompilerar för mig.

This compiles

---

AttendanceSchedule.yaml
common.yaml
openapi.yaml
paths/attendanceSchedules.yaml
paths/deletedEntities.yaml
todo.txt

Det heter inte barnomsorg längre i sverige av politiska skäl då detta nu är pedagogisk verksamhet. 
child care schedule => attendance schedule.
barnomsorgsschema => vistelseschema.

Döpte om barnomsorgsschema till vistelseschema.

---

Duty.yaml
paths/duties.yaml

Om man gör så här så blir det ju duty större men det kommer liksom på köpet

assignedToStudentGroupAs as a first class on Duty

---

Subscription.yaml
common.yaml
openapi.yaml
paths/deletedEntities.yaml
paths/subscriptions.yaml

Man bör kunna söka efter deletes och prenumerera på ändringar.
De kommer behöva ID:n också.

Attendance-typer till deleted och subscriptions

---

Person.yaml

Så vi kan återspegla värdet från skatteverket.

Fixed security marking

---

paths/schoolUnits.yaml

Att kunna söka fram en skolenhet från skolverkets skolenhetskod måste vara givet.

There must be a way to search by the SkolEnhetskod

---

Person.yaml
StudentGroup.yaml
paths/persons.yaml

Man måste kunna få en så komplett bild som möjligt från Person och sakerna i _embedded är väsentliga för detta. Att kunna få ut vilken klass och vilka undervisningsgrupper en person ingår i måste ingå.

Added an embedded array of StudentGroups on Person

---

AttendanceEvent.yaml
paths/attendanceEvents.yaml
paths/subscriptions.yaml

Fixade värdet under _embedded. 
Detta hade inte uppdaterats med att vi uppdaterat referensen från child => person

Fix av _embedded värdet för person

---

Absence.yaml
Attendance.yaml
AttendanceEvent.yaml
AttendanceSchedule.yaml
Subscription.yaml
openapi.yaml
paths/absences.yaml
paths/activities.yaml
paths/aggregatedAttendances.yaml
paths/attendanceEvents.yaml
paths/attendanceSchedules.yaml
paths/attendances.yaml
paths/calendarEvents.yaml
paths/deletedEntities.yaml
paths/duties.yaml
paths/grades.yaml
paths/organisations.yaml
paths/persons.yaml
paths/placements.yaml
paths/programmes.yaml
paths/resources.yaml
paths/rooms.yaml
paths/schoolUnitOfferings.yaml
paths/schoolUnits.yaml
paths/studentGroups.yaml
paths/studyPlans.yaml
paths/subscriptions.yaml
paths/syllabuses.yaml

Det var blandat med engelska och svenska beskrivningar.

Fix responses

---

AggregatedAttendance.yaml
AttendanceEvent.yaml
Duty.yaml
Person.yaml
Placement.yaml
SchoolUnit.yaml
StudentGroup.yaml
paths/placements.yaml
paths/studentGroups.yaml

Removed all Fragment object (made no sense)

Fix fragmented embeds

---

CalendarEvent.yaml
Enrolment.yaml
Person.yaml
Placement.yaml
StudyPlan.yaml
common.yaml
openapi.yaml

Added ObjectReferences with displayName to a lot of UUID references.

Add display name

---

common.yaml

Både wordfilen och kommentaren sa att avdelning skall vara med men inte mentor.
Eventuellt så behöver mentor också vara med, men då måste vi även ändra i Doc.

Fixed the StudentGroupType

---

Group.yaml
Organisation.yaml
Person.yaml
paths/absences.yaml
paths/calendarEvents.yaml
paths/duties.yaml
paths/grades.yaml
paths/groups.yaml
paths/persons.yaml
paths/placements.yaml
paths/programmes.yaml
paths/searchParameters.yaml
paths/studyPlans.yaml
paths/syllabuses.yaml

Fix membership

---

Absence.yaml
Activity.yaml
Enrolment.yaml
Person.yaml
common.yaml

La till provgrupps typ på aktivitet / grupp
Ändrade attributet (Absence) schoolUnit => organisation för att matcha entitets typen.

Provgrupper och attributnamn. 

---

LogEntry.yaml
openapi.yaml
paths/log.yaml

Added endpoints for providing feedback (errors and statistics)

Add feedback endpoints

---

Organisation.yaml
Subscription.yaml
openapi.yaml
paths/absences.yaml
paths/activities.yaml
paths/attendanceEvents.yaml
paths/attendanceSchedules.yaml
paths/attendances.yaml
paths/calendarEvents.yaml
paths/duties.yaml
paths/grades.yaml
paths/groups.yaml
paths/organisations.yaml
paths/persons.yaml
paths/placements.yaml
paths/programmes.yaml
paths/resources.yaml
paths/rooms.yaml
paths/schoolUnitOfferings.yaml
paths/syllabuses.yaml

Uppdaterade parametrar och lookups 

---

Absence.yaml
Group.yaml
Organisation.yaml
Programme.yaml
Syllabus.yaml
common.yaml

Also Changed the enum for organisation contactInfoType (public => publik). Because all other enums are in swedish!

Removed descriptions for linked Enums. (Fix for issue #88)

---

paths/activities.yaml

Resolves issue #98
Clarifies the id:s used in activity lookups.

Fixed Activity returntype and lookup parameters

---

Grade.yaml

Removed schoolUnit, registeredBy as mandatory fields.
Added syllabus as mandatory (in accordance with the word documentation)

Changed schoolUnit attribute to organisation

---

paths/activities.yaml

Fix for #107 that allows the activities endpoint to filter on active time periods for activities.

Add date filtering capabilities to the activities endpoint

---

paths/persons.yaml

PR for issue #113 
Adds groupMembership as a filter type for the relationship.entity.type filter on the persons endpoint.

Add groupMembership filter type to persons endpoint
